version: 2.1

jobs:
  gpu_linux:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#available-linux-gpu-images
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            source .circleci/setup_env.sh
      - run:
          name: Tests
          command: |
            source .circleci/setup_env.sh
            pytest -v
      # - run:
      #     name: TorchBench
      #     command: |
      #       source .circleci/setup_env.sh
      #       python benchmarks/torchbench.py -d cuda --raise


workflows:
  gpu:
    jobs:
      - gpu_linux
