version: 2.1

jobs:
  torchbench_linux_gpu:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#available-linux-gpu-images
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            source .circleci/setup_env.sh
            make setup
            python setup.py develop
      - run:
          name: Tests
          command: |
            source .circleci/setup_env.sh
            pytest


workflows:
  torchbench:
    jobs:
      - torchbench_linux_gpu
