version: 2.1

jobs:
  gpu_linux:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#available-linux-gpu-images
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            source .circleci/setup_env.sh
      - run:
          name: Tests
          command: |
            source .circleci/setup_env.sh
            mkdir test-results
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - run:
          name: TorchBench Install
          command: |
            source .circleci/setup_env.sh
            export GIT_LFS_SKIP_SMUDGE=1
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            # The latest git-lfs doesn't work with torchbench, need to use an old one
            sudo apt-get install git-lfs=2.13.2
            git clone --recursive --depth=1 --shallow-submodules git@github.com:jansel/benchmark.git torchbenchmark
            cd torchbenchmark
            git lfs install
            git lfs fetch
            git lfs checkout .
            python install.py
            cd ..
      - run:
          name: TorchBench Run
          command: |
            source .circleci/setup_env.sh
            python benchmarks/torchbench.py --coverage -dcuda --raise-on-backend-error
      - store_artifacts:
          path: coverage.csv

workflows:
  gpu:
    jobs:
      - gpu_linux
