name: Torchbench - cuda - inductor - BERT_pytorch

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-inductor:
    runs-on: linux.8xlarge.nvidia.gpu
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master
      with:
        repository: pytorch/benchmark
        path: ci_torchbenchmark
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64' 
        cache: 'pip'
    - run: which python
    - run: python --version
    - run: make setup_nightly
    # Note: this is here for iteration, we will add a `make torchbench_deps` for deps that torchbench has outside of dynamo
    - run: pip install pandas
    - run: pip install scipy
    - run: ./torchbench.py -k BERT_pytorch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
