name: Torchbench - cuda - inductor - BERT_pytorch

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-inductor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
    - uses: actions/checkout@master
      with:
        name: pytorch/benchmark
        path: torchbenchmark
    - run: make setup_nightly
    # Note: this is here for iteration, we will add a `make torchbench_deps` for deps that torchbench has outside of dynamo
    - run: pip install pandas
    - run: pip install scipy
    - run: ./torchbench.py -dcuda --inductor -k BERT_pytorch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
