name: Test Inductor

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-inductor:
    runs-on: linux.4xlarge.nvidia.gpu
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.13'
        cache: 'pip'
    - run: make setup_nightly_gpu
    - run: make develop
    - run: pytest ./test/test_torchinductor.py

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
