name: Test Inductor

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-inductor:
    runs-on: linux.4xlarge.nvidia.gpu
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        activate-environment: build
        miniconda-version: 4.12.0
    - run: make setup_nightly_gpu
    - run: make develop
    - run: pytest ./test/test_torchinductor.py

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
